owners = []
nickname = "bawt"
alt_nicks = ["stormyrs", "sunnyrs"]
username = "Stormy"
realname = "Stormy"
server = "irc.servercentral.net"
port = 6667
use_ssl = false
encoding = "UTF-8"
channels = ["#linuxgeneration", "#trey"]
umodes = "+RB-x"
user_info = "I'm a bawt."
version = "irc:git:Rust"
source = "https://github.com/aatxe/irc"
ping_time = 180
ping_timeout = 10
burst_window_length = 8
max_messages_in_burst = 15
should_ghost = false
ghost_sequence = []

[options]
openweathermap_appid = "8aa923241cb3621dcb8ffb6f9b45e0c8"
